version: 2
updates:
- package-ecosystem: uv
  directory: /
  schedule:
    interval: weekly
    time: '00:45'
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
    time: '00:45'
