name: Test application running state and increase version
on:
  push:
    branches: [ "master" ]
    paths:
      - "**/*.py"    
  workflow_dispatch:
permissions: read-all
jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13", "3.14"]
    name: Test with Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install UV
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv sync
      - name: Execute the CI script
        run: |
          chmod +x ci.sh
          bash ci.sh
  bump-version:
    needs: validate
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: Increase the version identifier
    steps:
      - uses: actions/checkout@v6
      - name: Install UV
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv sync
      - name: Bump patch version
        run: uv run hatch version beta
      - name: Commit and push bumped version
        run: |
          git config user.name "GHActionBot"
          git config user.email "gha@github.com"
          git commit -m "chore: bump version" src/wpr/__about__.py
          git push
